### PR TITLE
adding catch block for inner try block

### PR DESCRIPTION
**Pull request by itsAftabAlam**
adding catch block for inner try block that could lead to potential exception

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did`

### CODE REVIEW

**Review by strangelookingnerd — COMMENTED** [review]
This just duplicates the outer `catch`-block, so there is no benefit for this unless I'm completely missing something. Any exception thrown would be caught by the outer `catch`-block anyways. Besides that the formatting is off.

**Comment by itsAftabAlam** [comment]
Thank you for the review. I agree this duplicates the code and might complicates the things, but can we use a try block independently without a catch or a finally block, syntax wise?

**Comment by strangelookingnerd** [comment]
> Thank you for the review. I agree this duplicates the code and might complicate the things, but can we use a try block independently without a catch or a finally block, syntax wise? I tried to fix that issue. Otherwise the plugin might break out of its normal execution flow at some point.

Yes you can do that by using `try-with-resources`-blocks :) 
See https://www.baeldung.com/java-try-with-resources for an explanation.

**Comment by itsAftabAlam** [comment]
> Yes you can do that by using `try-with-resources`-blocks :) See https://www.baeldung.com/java-try-with-resources for an explanation.
Thank you for the info and giving your time to review this PR :) The code now looks good to me without the PR also. You might close the PR!

**Pull request closed without merging**
